# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 6b483c6ee8def5cc24828f203d6d1b8ee508441c47fda75ad4c6606f7e90155ac365ebd9d74c06c8b21817174c0e53df9cba2f723ca39d507211493c20a1c033

test:
  domain_name: example.com 
  secret_key_base: 9595390a4076c0cbf403ec437a2dceb1287cbfafae8104cb86e1b89421231101f084cd1f7a74ae0cf641bacc7f500c3a844f1e618b83eaf19e98a9accd4774c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
